[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

remappings = [
    "@erc6900/=lib/reference-implementation/",
    "@eth-infinitism/account-abstraction/=lib/account-abstraction/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]